[package]
name = "secret-santa"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
cmd_lib = "1.9.5"
ron = "0.8.1"
satoxid = "0.1.2"
serde = { version = "1.0.215", features = ["derive"] }
